# Documentation https://s.apache.org/asfyaml
staging:
  profile: ~
  whoami:  asf-staging

publish:
  whoami:  asf-site

jekyll:
  whoami: master
  target: asf-site

github:
  del_branch_on_merge: true
