name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
source:         source
encoding:       UTF-8
highlighter:    rouge
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Simplifies introducing changes related to the latest release
current_version: 6.2.0
current_version_short: 620
prev_version: 6.1.2.1
prev_25_version: 2.5.31
prev_version_short: 6121
archetype_version: 6.0.0
release_date: 10 July 2023
prev_release_date: 13 June 2023
prev_25_release_date: 13 June 2023
release_date_short: 20230710
prev_release_date_short: 20230613-1
prev_25_release_date_short: 20230613-2
beta_release_date_short: 20160126

# Allows directly edit pages on GitHub
repository_url: https://github.com/apache/struts-site

# Used to generate links to Struts Core ApiDocs
apidocs: /maven/struts2-core/apidocs

# Confluence main site
wiki_url: https://cwiki.apache.org/confluence/display/WW

# Archive site with all the versions
archive_url: https://archive.apache.org/dist/struts/

# JIRA issue tracking
jira_url: https://issues.apache.org/jira/projects/WW/
