name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
source:         source
encoding:       UTF-8
highlighter:    rouge
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Simplifies introducing changes related to the latest release
current_version: 6.1.2
current_version_short: 612
prev_version: 2.5.30
prev_version_short: 2530
archetype_version: 6.0.0
release_date: 10 March 2023
release_date_short: 20230310
beta_release_date_short: 20160126

# Allows directly edit pages on GitHub
repository_url: https://github.com/apache/struts-site

# Used to generate links to Struts Core ApiDocs
apidocs: /maven/struts2-core/apidocs

# Confluence main site
wiki_url: https://cwiki.apache.org/confluence/display/WW

# Archive site with all the versions
archive_url: https://archive.apache.org/dist/struts/

# JIRA issue tracking
jira_url: https://issues.apache.org/jira/projects/WW/
